[package]
name = "diffie_hellman_key_exchange_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
glass_pumpkin = "1.2.0"
num-bigint ={version = "0.4.0", features = ["rand"]}